# SPDX-FileCopyrightText: © 2026 Varun R Mallya
# SPDX-License-Identifier: Apache-2.0
"""Cocotb tests for the hardcaml-generated UART transmitter.

The RTL under test is generated by ``make rtl`` from ``hardcaml/``; these tests
run against that verilog (RTL sim) and, in CI, against the gate level netlist.

Pinout (see info.yaml):
    ui_in[7:0]  byte to transmit
    uio_in[0]   start strobe
    uo_out[0]   uart tx line (idles high)
    uo_out[1]   busy
"""

import re
from pathlib import Path

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import ClockCycles, RisingEdge

RTL = Path(__file__).parent.parent / "src" / "tt_um_uart_tx.v"


def design_parameters():
    """Read the clock/baud the RTL was generated with out of its header.

    The generator stamps them into src/tt_um_uart_tx.v, so `make rtl
    CLOCK_HZ=... BAUD=...` retargets the design and these tests together
    instead of leaving a hardcoded constant here to rot.
    """
    header = RTL.read_text()[:1000]
    match = re.search(r"clock = (\d+)Hz, baud = (\d+), cycles/bit = (\d+)", header)
    assert match, f"could not read the generated header of {RTL}"
    clock_hz, _baud, cycles_per_bit = (int(g) for g in match.groups())
    return round(1e9 / clock_hz), cycles_per_bit


CLOCK_PERIOD_NS, CYCLES_PER_BIT = design_parameters()


def tx(dut):
    return int(dut.uo_out.value) & 1


def busy(dut):
    return (int(dut.uo_out.value) >> 1) & 1


async def start_clock_and_reset(dut):
    cocotb.start_soon(Clock(dut.clk, CLOCK_PERIOD_NS, unit="ns").start())
    dut.ena.value = 1
    dut.ui_in.value = 0
    dut.uio_in.value = 0
    dut.rst_n.value = 0
    await ClockCycles(dut.clk, 5)
    dut.rst_n.value = 1
    await ClockCycles(dut.clk, 1)


async def receive_byte(dut):
    """Decode one 8N1 frame off the tx pin, sampling in the middle of each bit."""
    # Wait for the falling edge that starts the frame.
    while tx(dut) == 1:
        await RisingEdge(dut.clk)
    # We are one cycle into the start bit; step to its middle.
    await ClockCycles(dut.clk, CYCLES_PER_BIT // 2 - 1)
    assert tx(dut) == 0, "start bit did not stay low"

    byte = 0
    for bit in range(8):
        await ClockCycles(dut.clk, CYCLES_PER_BIT)
        byte |= tx(dut) << bit

    await ClockCycles(dut.clk, CYCLES_PER_BIT)
    assert tx(dut) == 1, f"bad stop bit after byte 0x{byte:02x}"
    return byte


async def transmit(dut, value):
    dut.ui_in.value = value
    dut.uio_in.value = 1
    await ClockCycles(dut.clk, 1)
    dut.uio_in.value = 0


@cocotb.test()
async def test_reset_idles_high(dut):
    """The line idles high and the core is not busy out of reset."""
    await start_clock_and_reset(dut)
    assert tx(dut) == 1, "tx should idle high"
    assert busy(dut) == 0, "should not be busy when idle"
    assert int(dut.uio_oe.value) == 0, "bidirectional pins are inputs only"


@cocotb.test()
async def test_transmit_bytes(dut):
    """Every byte comes back out of the tx pin, framed correctly."""
    await start_clock_and_reset(dut)
    for value in (0x5A, 0xA5, 0x00, 0xFF, 0x0F):
        received = cocotb.start_soon(receive_byte(dut))
        await transmit(dut, value)
        got = await received
        assert got == value, f"sent 0x{value:02x}, received 0x{got:02x}"
        # Drain the stop bit before queuing the next byte.
        await ClockCycles(dut.clk, CYCLES_PER_BIT)
        assert busy(dut) == 0, "still busy after the stop bit"


@cocotb.test()
async def test_busy_ignores_new_requests(dut):
    """A strobe while busy must not corrupt the frame in flight."""
    await start_clock_and_reset(dut)
    received = cocotb.start_soon(receive_byte(dut))
    await transmit(dut, 0x3C)
    await ClockCycles(dut.clk, CYCLES_PER_BIT)
    assert busy(dut) == 1, "busy should be asserted while transmitting"
    # Bang on the strobe with different data mid-frame.
    for _ in range(4):
        await transmit(dut, 0xFF)
        await ClockCycles(dut.clk, CYCLES_PER_BIT // 2)
    got = await received
    assert got == 0x3C, f"frame corrupted by a strobe while busy: 0x{got:02x}"


@cocotb.test()
async def test_ena_gates_transmission(dut):
    """With ena low the design is deselected and must stay quiet."""
    await start_clock_and_reset(dut)
    dut.ena.value = 0
    await transmit(dut, 0x55)
    await ClockCycles(dut.clk, 4 * CYCLES_PER_BIT)
    assert tx(dut) == 1, "transmitted while deselected"
    assert busy(dut) == 0, "busy while deselected"
    dut.ena.value = 1
