/* Generated by hardcaml - do not edit.
   Regenerate with `make rtl`.
   clock = 50000000Hz, baud = 115200, cycles/bit = 434 */
`default_nettype none
module uart_tx (
    clock,
    clear,
    data,
    data_valid,
    tx,
    busy
);

    input clock;
    input clear;
    input [7:0] data;
    input data_valid;
    output tx;
    output busy;

    wire signal_eq;
    wire busy_0;
    wire vdd;
    wire signal_select;
    wire signal_mux;
    wire signal_mux_1;
    wire [7:0] signal_const;
    wire [6:0] signal_select_1;
    wire signal_const_1;
    wire [7:0] signal_cat;
    wire [7:0] signal_mux_2;
    wire [7:0] signal_wire;
    wire [7:0] signal_mux_3;
    reg [7:0] signal_cases;
    wire [7:0] signal_wire_1;
    reg [7:0] signal_reg;
    wire signal_select_2;
    wire signal_mux_4;
    wire gnd;
    wire signal_mux_5;
    wire [1:0] signal_const_2;
    wire [1:0] signal_mux_6;
    wire [1:0] signal_const_11;
    wire [2:0] signal_const_3;
    wire [2:0] signal_const_4;
    wire [2:0] signal_const_5;
    wire [2:0] signal_add;
    wire [2:0] signal_mux_7;
    wire [2:0] signal_mux_8;
    wire [2:0] signal_mux_9;
    reg [2:0] signal_cases_1;
    wire [2:0] signal_wire_2;
    reg [2:0] signal_reg_1;
    wire signal_eq_1;
    wire [1:0] signal_mux_10;
    wire [1:0] signal_mux_11;
    wire [1:0] signal_const_14;
    wire [8:0] signal_const_7;
    wire [8:0] signal_const_8;
    wire signal_wire_3;
    wire signal_wire_4;
    wire [8:0] signal_const_10;
    wire [8:0] signal_add_1;
    wire [8:0] signal_mux_12;
    wire [8:0] signal_add_2;
    wire [8:0] signal_mux_13;
    wire [8:0] signal_add_3;
    wire [8:0] signal_mux_14;
    wire [8:0] signal_mux_15;
    reg [8:0] signal_cases_2;
    wire [8:0] signal_wire_5;
    reg [8:0] baud_counter;
    wire signal_eq_2;
    wire [1:0] signal_mux_16;
    wire [1:0] signal_const_18;
    wire signal_wire_6;
    wire [1:0] signal_mux_17;
    reg [1:0] signal_cases_3;
    wire [1:0] signal_wire_7;
    (* fsm_encoding="one_hot" *)
    reg [1:0] state;
    reg signal_cases_4;
    wire signal_wire_8;
    reg tx_0;
    assign signal_eq = signal_const_2 == state;
    assign busy_0 = ~ signal_eq;
    assign vdd = 1'b1;
    assign signal_select = signal_reg[1:1];
    assign signal_mux = signal_eq_1 ? vdd : signal_select;
    assign signal_mux_1 = signal_eq_2 ? signal_mux : tx_0;
    assign signal_const = 8'b00000000;
    assign signal_select_1 = signal_reg[7:1];
    assign signal_const_1 = 1'b0;
    assign signal_cat = { signal_const_1,
                          signal_select_1 };
    assign signal_mux_2 = signal_eq_2 ? signal_cat : signal_reg;
    assign signal_wire = data;
    assign signal_mux_3 = signal_wire_6 ? signal_wire : signal_reg;
    always @* begin
        case (state)
        2'b00:
            signal_cases <= signal_mux_3;
        2'b10:
            signal_cases <= signal_mux_2;
        default:
            signal_cases <= signal_reg;
        endcase
    end
    assign signal_wire_1 = signal_cases;
    always @(posedge signal_wire_4) begin
        if (signal_wire_3)
            signal_reg <= signal_const;
        else
            signal_reg <= signal_wire_1;
    end
    assign signal_select_2 = signal_reg[0:0];
    assign signal_mux_4 = signal_eq_2 ? signal_select_2 : tx_0;
    assign gnd = 1'b0;
    assign signal_mux_5 = signal_wire_6 ? gnd : tx_0;
    assign signal_const_2 = 2'b00;
    assign signal_mux_6 = signal_eq_2 ? signal_const_2 : state;
    assign signal_const_11 = 2'b11;
    assign signal_const_3 = 3'b111;
    assign signal_const_4 = 3'b000;
    assign signal_const_5 = 3'b001;
    assign signal_add = signal_reg_1 + signal_const_5;
    assign signal_mux_7 = signal_eq_1 ? signal_reg_1 : signal_add;
    assign signal_mux_8 = signal_eq_2 ? signal_mux_7 : signal_reg_1;
    assign signal_mux_9 = signal_wire_6 ? signal_const_4 : signal_reg_1;
    always @* begin
        case (state)
        2'b00:
            signal_cases_1 <= signal_mux_9;
        2'b10:
            signal_cases_1 <= signal_mux_8;
        default:
            signal_cases_1 <= signal_reg_1;
        endcase
    end
    assign signal_wire_2 = signal_cases_1;
    always @(posedge signal_wire_4) begin
        if (signal_wire_3)
            signal_reg_1 <= signal_const_4;
        else
            signal_reg_1 <= signal_wire_2;
    end
    assign signal_eq_1 = signal_reg_1 == signal_const_3;
    assign signal_mux_10 = signal_eq_1 ? signal_const_11 : state;
    assign signal_mux_11 = signal_eq_2 ? signal_mux_10 : state;
    assign signal_const_14 = 2'b10;
    assign signal_const_7 = 9'b110110001;
    assign signal_const_8 = 9'b000000000;
    assign signal_wire_3 = clear;
    assign signal_wire_4 = clock;
    assign signal_const_10 = 9'b000000001;
    assign signal_add_1 = baud_counter + signal_const_10;
    assign signal_mux_12 = signal_eq_2 ? signal_const_8 : signal_add_1;
    assign signal_add_2 = baud_counter + signal_const_10;
    assign signal_mux_13 = signal_eq_2 ? signal_const_8 : signal_add_2;
    assign signal_add_3 = baud_counter + signal_const_10;
    assign signal_mux_14 = signal_eq_2 ? signal_const_8 : signal_add_3;
    assign signal_mux_15 = signal_wire_6 ? signal_const_8 : baud_counter;
    always @* begin
        case (state)
        2'b00:
            signal_cases_2 <= signal_mux_15;
        2'b01:
            signal_cases_2 <= signal_mux_14;
        2'b10:
            signal_cases_2 <= signal_mux_13;
        2'b11:
            signal_cases_2 <= signal_mux_12;
        default:
            signal_cases_2 <= baud_counter;
        endcase
    end
    assign signal_wire_5 = signal_cases_2;
    always @(posedge signal_wire_4) begin
        if (signal_wire_3)
            baud_counter <= signal_const_8;
        else
            baud_counter <= signal_wire_5;
    end
    assign signal_eq_2 = baud_counter == signal_const_7;
    assign signal_mux_16 = signal_eq_2 ? signal_const_14 : state;
    assign signal_const_18 = 2'b01;
    assign signal_wire_6 = data_valid;
    assign signal_mux_17 = signal_wire_6 ? signal_const_18 : state;
    always @* begin
        case (state)
        2'b00:
            signal_cases_3 <= signal_mux_17;
        2'b01:
            signal_cases_3 <= signal_mux_16;
        2'b10:
            signal_cases_3 <= signal_mux_11;
        2'b11:
            signal_cases_3 <= signal_mux_6;
        default:
            signal_cases_3 <= state;
        endcase
    end
    assign signal_wire_7 = signal_cases_3;
    always @(posedge signal_wire_4) begin
        if (signal_wire_3)
            state <= signal_const_2;
        else
            state <= signal_wire_7;
    end
    always @* begin
        case (state)
        2'b00:
            signal_cases_4 <= signal_mux_5;
        2'b01:
            signal_cases_4 <= signal_mux_4;
        2'b10:
            signal_cases_4 <= signal_mux_1;
        default:
            signal_cases_4 <= tx_0;
        endcase
    end
    assign signal_wire_8 = signal_cases_4;
    always @(posedge signal_wire_4) begin
        if (signal_wire_3)
            tx_0 <= vdd;
        else
            tx_0 <= signal_wire_8;
    end
    assign tx = tx_0;
    assign busy = busy_0;

endmodule
module tt_um_uart_tx (
    ui_in,
    uio_in,
    ena,
    clk,
    rst_n,
    uo_out,
    uio_out,
    uio_oe
);

    input [7:0] ui_in;
    input [7:0] uio_in;
    input ena;
    input clk;
    input rst_n;
    output [7:0] uo_out;
    output [7:0] uio_out;
    output [7:0] uio_oe;

    wire [7:0] signal_const;
    wire signal_select;
    wire signal_wire;
    wire [7:0] signal_wire_1;
    wire signal_select_1;
    wire signal_and;
    wire [7:0] signal_wire_2;
    wire signal_wire_3;
    wire signal_not;
    wire signal_wire_4;
    wire [1:0] signal_inst;
    wire signal_select_2;
    wire [5:0] signal_const_2;
    wire [7:0] signal_cat;
    assign signal_const = 8'b00000000;
    assign signal_select = signal_inst[0:0];
    assign signal_wire = ena;
    assign signal_wire_1 = uio_in;
    assign signal_select_1 = signal_wire_1[0:0];
    assign signal_and = signal_select_1 & signal_wire;
    assign signal_wire_2 = ui_in;
    assign signal_wire_3 = rst_n;
    assign signal_not = ~ signal_wire_3;
    assign signal_wire_4 = clk;
    uart_tx
        uart_tx
        ( .clock(signal_wire_4),
          .clear(signal_not),
          .data(signal_wire_2),
          .data_valid(signal_and),
          .tx(signal_inst[0:0]),
          .busy(signal_inst[1:1]) );
    assign signal_select_2 = signal_inst[1:1];
    assign signal_const_2 = 6'b000000;
    assign signal_cat = { signal_const_2,
                          signal_select_2,
                          signal_select };
    assign uo_out = signal_cat;
    assign uio_out = signal_const;
    assign uio_oe = signal_const;

endmodule

`default_nettype wire
